### PR TITLE
Merging updates from upstream

### PR DESCRIPTION
**Pull request by karelbilek**
I am unable to make PR for rebasing your branch on top of upstream (naturally)

So I am at least making PR for putting them on top :)

Fixes https://github.com/str4d/insight-ui-zcash/issues/2

What's really important for me is just the queryMempoolOnly commit ( https://github.com/str4d/bitcore-node-zcash/commit/b92d4340a144b61bdc7247dbccfd44aed07500cc ), I don't really care about the rest :))

### CODE REVIEW

**Comment by str4d** [comment]
I think I *will* want to merge this in, rather than rebasing (since I'm not versioning the Zcash-specific branch). But I don't have time to review this until after Zcash 1.0.4 is released.

**Comment by karelbilek** [comment]
Thx. As you wish.

**Comment by karelbilek** [comment]
Ping

**Comment by karelbilek** [comment]
If you don't want to review all the changes - I can make a new pull request with just the one important change, which is this commit

https://github.com/str4d/bitcore-node-zcash/pull/2/commits/b92d4340a144b61bdc7247dbccfd44aed07500cc

**Comment by slush0** [comment]
Hi @str4d, merging all pending PRs from @runn1ng would make our life much easier. Thanks in advance :).

**Comment by karelbilek** [comment]
Oh. Now there are commits from bitpay:master being merged here; and new bitpay:master is based on bcoin (basically entirely new backend). So this PR is basically useless now.

**Comment by karelbilek** [comment]
Closing this issue, I keep getting useless notifications. :)

**Pull request closed without merging**
